config/routes.rb
Rails.application.routes.draw do
  
  resources :flights do
    collection { post :import }
  end
  
  get 'flights/index'

  get 'flights/import'
  
  root to: "flights#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
require 'csv'
require 'roo'

class Flight < ApplicationRecord
    
    @rows = Array.new
    @header = Array.new
    def self.import(file)
        CSV.foreach(file.path, headers: false) do |row|
            @rows << row
        end
        header = @rows.shift
        @rows.each do |row|
            create_flight(row[0].split("\t"))
        end
    end
    
    def self.is_a_departure?
        self.scheddepapt == 'LGA'
    end
    
    def self.departures
        @flights = Flight.all
        deps = Array.new
        @flights.each do |flight|
            if flight.scheddepapt == 'LGA' && flight.schedarrapt != 'LGA'
                deps << flight
            end
        end
        deps
    end
    
    def self.arrivals
        @flights = Flight.all
        arrs = Array.new
        @flights.each do |flight|
            if flight.scheddepapt != 'LGA' && flight.schedarrapt == 'LGA'
                arrs << flight
            end
        end
        arrs
    end
    
    def self.turns
        tours = Array.new
        depar = Flight.departures
        arriv = Flight.arrivals
        
        depar.sort_by! {|dep| dep.airlinecode}
        arriv.sort_by! {|arr| arr.airlinecode}
        
        depar.each do |dep|
            found = false
            arriv.each do |arr|
                if dep.tailnumber == arr.tailnumber && found == false
                    tours << [arr, dep]
                    found = true
                end
            end
        end
        tours
    end
    
    private
    
    def self.create_flight(row)
        Flight.create!
        flight = Flight.last
        flight.assign_attributes(
            flightid: row[0],
            airlinecode: row[1],
            flightnumber: row[2],
            scheddepapt: row[3],
            schedarrapt: row[4],
            scheddeputc: row[5],
            schedarrutc: row[6],
            scheddeplocal: row[7],
            schedarrlocal: row[8],
            diversionstatus: row[9],
            recovflightid: row[10],
            opairlinecode: row[11],
            opflightnumber: row[12],
            altdepapt: row[13],
            altarrapt: row[14],
            depterminal: row[15],
            depgate: row[16],
            arrterminal: row[17],
            arrgate: row[18],
            baggage: row[19],
            servicetype: row[20],
            aircrafttype: row[21],
            unscheduled: row[22],
            depcountrycode: row[23],
            arrcountrycode: row[24],
            tailnumber: row[25],
            regairlinecode: row[26],
            regflightnumber: row[27],
            origdate: row[28],
            prevfltalcode: row[29],
            prevfltnumber: row[30],
            prevfltschedarrlocal: row[31],
            prevfltschedarrutc: row[32],
            outgatelocal: row[33],
            outgateutc: row[34],
            outgateaccuracy: row[35],
            inairlocal: row[36],
            inairutc: row[37],
            inairaccuracy: row[38],
            landedlocal: row[39],
            landedutc: row[40],
            landedaccuracy: row[41],
            ingatelocal: row[42],
            ingateutc: row[43],
            ingateaccuracy: row[44],
            diversiontype: row[45],
            simplemaxalt: row[46],
            simpleavgalt: row[47],
            simplemaxspeed: row[48],
            simpleavgspeed: row[49],
            distancegc: row[50],
            timealoft: row[51],
            cancelled: row[52],
            acttaxitimedep: row[53],
            acttaxitimearr: row[54],
            minlatedeparted: row[55],
            minlatearrived: row[56]
        )
        flight.save!

        p "Flight #{flight.airlinecode}#{flight.flightnumber} flying from #{flight.schedarrapt} to #{flight.scheddepapt} has been created!\n"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    @arrs = Flight.arrivals
    @deps = Flight.departures
    @turns = Flight.turns
  end

  def import
    Flight.import(params[:file])
    redirect_to root_url, notice: "Flight Data imported!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/import.html.erb
<h1>Flights#import</h1>
<p>Find me in app/views/flights/import.html.erb</p>

app/views/flights/index.html.erb
<%= flash[:notice] %>
<div>
    <h4 class="deepshadow">Flight Data</h4>
        <%= form_tag import_flights_path, multipart: true do %>
            <%= file_field_tag :file %>
            <%= submit_tag "Import CSV", :class => 'myButton' %>
        <% end %>
</div>
<table>
<%
=begin
%>
    <thead>
        <tr>
            <th>Airline</th>
            <th>Flight Number</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Schedule Departure</th>
            <th>Departure Terminal</th>
            <th>Departure Gate</th>
            <th>Aircraft Type</th>
            <th>Tail Number</th>
            <th>Off Block</th>
            <th>Take Off Time</th>
            <th>Cancelled</th>
            <th>Time on Runway</th>
            <th>Minutes Late Departed</th>
        </tr>
    </thead>

    <tbody>
        <% @flights.each do |flight| %>
            <% if flight.scheddepapt == "LGA" && flight.depterminal == 'B' && flight.airlinecode == 'UA' && flight. %>
                <tr>
                    <td><%= flight.airlinecode %></td>
                    <td><%= flight.flightnumber %></td>
                    <td><%= flight.scheddepapt %></td>
                    <td><%= flight.schedarrapt %></td>
                    <td><%= flight.scheddeplocal %></td>
                    <td><%= flight.depterminal %></td>
                    <td><%= flight.depgate %></td>
                    <td><%= flight.aircrafttype %></td>
                    <td><%= flight.tailnumber %></td>
                    <td><%= flight.outgatelocal %></td>
                    <td><%= flight.inairlocal %></td>
                    <td><%= flight.cancelled %></td>
                    <td><%= flight.acttaxitimedep %></td>
                    <td><%= flight.minlatedeparted %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
<%
=end
%>
    <thead>
        <tr>
            <th>Arrival</th>
            <th>Departure</th>
            <th>TailNumber</th>
            <th>Arrival's Airport</th>
            <th>Departure's Airport</th>
            <th>Departure's Terminal</th>
            <th>Arrival's Terminal</th>
            <th>Arrival's Gate</th>
            <th>Departure's Gate</th>
        </tr>
    </thead>
    <tbody>
        <% @flights.each do |couple| %>
            <% if couple.depterminal == "B" && couple.arrterminal == 'B' %>
                <tr>
                    <td><%= couple.airlinecode %> | <%= couple.flightnumber %></td>
                    <td><%= couple.airlinecode %> | <%= couple.flightnumber %></td>
                    <td><%= couple.tailnumber %> | <%= couple.tailnumber %></td>
                    <td><%= couple.schedarrapt %></td>
                    <td><%= couple.scheddeplocal %></td>
                    <td><%= couple.depterminal %></td>
                    <td><%= couple.arrterminal %></td>
                    <td><%= couple.arrgate %></td>
                    <td><%= couple.depgate %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flightstats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>